name: "PraiseCharts"
click:
  downbeat: "PraiseCharts/PraiseCharts Downbeat.wav"
  upbeat: "PraiseCharts/PraiseCharts Upbeat.wav"
  between: "PraiseCharts/PraiseCharts Midbeat.wav"
cues:
  by_section:
    lead: "English Guides/Song Sections/English Female - Intro.wav"
    count_in: "English Guides/Song Sections/English Female - Intro.wav"
    intro: "English Guides/Song Sections/English Female - Intro.wav"
    verse: "English Guides/Song Sections/English Female - Verse.wav"
    verse_1: "English Guides/Song Sections/English Female - Verse 1.wav"
    verse_2: "English Guides/Song Sections/English Female - Verse 2.wav"
    verse_3: "English Guides/Song Sections/English Female - Verse 3.wav"
    verse_4: "English Guides/Song Sections/English Female - Verse 4.wav"
    verse_5: "English Guides/Song Sections/English Female - Verse 5.wav"
    verse_6: "English Guides/Song Sections/English Female - Verse 6.wav"
    chorus: "English Guides/Song Sections/English Female - Chorus.wav"
    chorus_1: "English Guides/Song Sections/English Female - Chorus 1.wav"
    chorus_2: "English Guides/Song Sections/English Female - Chorus 2.wav"
    chorus_3: "English Guides/Song Sections/English Female - Chorus 3.wav"
    chorus_4: "English Guides/Song Sections/English Female - Chorus 4.wav"
    bridge: "English Guides/Song Sections/English Female - Bridge.wav"
    bridge_1: "English Guides/Song Sections/English Female - Bridge 1.wav"
    bridge_2: "English Guides/Song Sections/English Female - Bridge 2.wav"
    bridge_3: "English Guides/Song Sections/English Female - Bridge 3.wav"
    bridge_4: "English Guides/Song Sections/English Female - Bridge 4.wav"
    pre_chorus: "English Guides/Song Sections/English Female - Pre Chorus.wav"
    post_chorus: "English Guides/Song Sections/English Female - Post Chorus.wav"
    refrain: "English Guides/Song Sections/English Female - Refrain.wav"
    interlude: "English Guides/Song Sections/English Female - Interlude.wav"
    interlude_1: "English Guides/Song Sections/English Female - Interlude.wav"
    turnaround: "English Guides/Song Sections/English Female - Turnaround.wav"
    vamp: "English Guides/Song Sections/English Female - Vamp.wav"
    instrumental: "English Guides/Song Sections/English Female - Instrumental.wav"
    outro: "English Guides/Song Sections/English Female - Outro.wav"
    ending: "English Guides/Song Sections/English Female - Ending.wav"
    tag: "English Guides/Song Sections/English Female - Tag.wav"
  by_count:
    "1": "English Guides/Song Sections/English Female - 1.wav"
    "2": "English Guides/Song Sections/English Female - 2.wav"
    "3": "English Guides/Song Sections/English Female - 3.wav"
    "4": "English Guides/Song Sections/English Female - 4.wav"
    "5": "English Guides/Song Sections/English Female - 5.wav"
    "6": "English Guides/Song Sections/English Female - 6.wav"
    "7": "English Guides/Song Sections/English Female - 7.wav"
